# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.


name: CI Pipeline — Smart Task Escalation Engine


on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    name: Lint · Test · Coverage

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8

      - name: Lint with flake8
        run: |
          flake8 services/ data/ tests/ \
            --max-line-length=100 \
            --ignore=E501,W503,E241,E221,E127,E302,E402,E401,E702,E741,F401 \
            --exclude=.venv
      - name: Show files
        run: |
          pwd
          ls -la
          find . -type d
    
      - name: Run tests with coverage
        run: |
          pytest tests/ -v \
            --cov=services \
            --cov=data \
            --cov-report=term-missing \
            --cov-report=html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: htmlcov/
